// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flwvvciveynkcwpkosdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsd3Z2Y2l2ZXlua2N3cGtvc2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjAwNzMsImV4cCI6MjA3MTk5NjA3M30.RDwphvcApJ_av-J39fwKHLVHfIvhfSB_hliXAt2LdXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});