// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhuzaityyuszvfrsgcgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxodXphaXR5eXVzenZmcnNnY2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTE3NTUsImV4cCI6MjA2MzY4Nzc1NX0.ZPgNiiGf-JZR8CQrvD7ujZeLD04GLtmEkereQka7N3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);